smart: smartpointers.cpp
	g++ smartpointers.cpp -std=c++20 -Wall -Werror -pedantic
	./a.out

unique: uniqueptr.cpp
	g++ uniqueptr.cpp -std=c++20 -Wall -Werror -pedantic
	./a.out
	
shared: sharedptr.cpp
	g++ sharedptr.cpp -std=c++20 -Wall -Werror -pedantic
	./a.out

weak: weakptr.cpp
	g++ weakptr.cpp -std=c++20 -Wall -Werror -pedantic
	./a.out