parw:
	g++ parallel_wrong.cpp -o parallel_wrong.out && ./parallel_wrong.out
parwp:
	g++ parallel_wrong_print.cpp -o parallel_wrong_print.out && ./parallel_wrong_print.out
deadlock:
	g++ deadlock.cpp -o deadlock.out && ./deadlock.out
cv:
	g++ condition_v.cpp -o condition_v.out && ./condition_v.out
example:
	g++ example.cpp -o example.out && ./example.out

clean:
	rm *.out
